# netlify.toml

# 1. Configurações de Build
[build]
  # Comando que a Netlify vai rodar. Ele executa o script "build" do seu package.json da raiz.
  command = "npm run build"
  
  # Onde os arquivos do seu front-end estarão após o build.
  publish = "frontend/dist"
  
  # Onde estão as funções da sua API (back-end).
  # Apontamos para a pasta que contém o 'api', para que a função seja nomeada corretamente.
  functions = "backend"

# 2. Redirecionamento para a API funcionar
# Esta é a correção mais importante.
[[redirects]]
  # Pega qualquer requisição que comece com /api/
  from = "/api/*"
  # E a envia para a função serverless que a Netlify criou a partir da pasta 'api'.
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true # Garante que esta regra tenha prioridade

# 3. Redirecionamento para o Vue Router funcionar (essencial para SPAs)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200